### ISSUE TITLE
Error executing action `create` on resource 'tickTime=2000

### ISSUE THREAD

**Issue by francoisnicholas** [bloomberg/zookeeper-cookbook#13]
I am unable to successfully converge the recipe to setup a two node cluster. See the full snippet below. Please can someone assist me by pointing me to what I am doing wrong? I also attached my very simple wrapper cookbook & the databag for the nodes. 
[data_bags.zip](https://github.com/bloomberg/zookeeper-cookbook/files/83056/data_bags.zip)
[lms-zookeeper-cluster.zip](https://github.com/bloomberg/zookeeper-cookbook/files/83055/lms-zookeeper-cluster.zip)

``` bash
[vagrant@node-centos65 ~]$ sudo chef-client -o recipe[lms-zookeeper-cluster] 
Starting Chef Client, version 12.6.0
[2016-01-08T17:36:44+00:00] WARN: Run List override has been provided.
[2016-01-08T17:36:44+00:00] WARN: Original Run List: []
[2016-01-08T17:36:44+00:00] WARN: Overridden Run List: [recipe[lms-zookeeper-cluster]]
resolving cookbooks for run list: ["lms-zookeeper-cluster"]
Synchronizing Cookbooks:
  - lms-zookeeper-cluster (0.1.0)
  - zookeeper-cluster (1.2.0)
  - java (1.36.0)
  - libartifact (1.3.3)
  - libarchive (0.6.1)
  - apt (2.9.2)
  - yum-epel (0.6.5)
  - yum (3.8.2)
  - poise (2.4.0)
  - poise-service (1.0.4)
  - selinux (0.9.0)
Compiling Cookbooks...
Converging 12 resources
Recipe: java::openjdk
  * yum_package[java-1.8.0-openjdk] action install (up to date)
  * yum_package[java-1.8.0-openjdk-devel] action install (up to date)
  * java_alternatives[set-java-alternatives] action set (up to date)
Recipe: java::set_java_home
  * ruby_block[set-env-java-home] action run
    - execute the ruby block set-env-java-home
  * directory[/etc/profile.d] action create (up to date)
  * file[/etc/profile.d/jdk.sh] action create (up to date)
Recipe: selinux::_common
  * yum_package[libselinux-utils] action install (up to date)
  * directory[/etc/selinux] action create (up to date)
Recipe: selinux::disabled
  * selinux_state[SELinux Disabled] action disabled (up to date)
Recipe: zookeeper-cluster::default
  * poise_service_user[zookeeper] action create
    * group[zookeeper] action create (up to date)
    * user[zookeeper] action create (up to date)
     (up to date)
  * tickTime=2000
  initLimit=5
  syncLimit=2
  leaderServes=yes
  forceSync=no
  dataDir=/var/lib/zookeeper
  leaderPort=2888
  clientPort=2181
  electionPort=3888
  server.1:node-centos65:2888:3888
  server.2:node2-centos65:2888:3888 action create

    ================================================================================
    Error executing action `create` on resource 'tickTime=2000
    initLimit=5
    syncLimit=2
    leaderServes=yes
    forceSync=no
    dataDir=/var/lib/zookeeper
    leaderPort=2888
    clientPort=2181
    electionPort=3888
    server.1:node-centos65:2888:3888
    server.2:node2-centos65:2888:3888'
    ================================================================================

    NoMethodError
    -------------
    undefined method `next' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/zookeeper-cluster/libraries/zookeeper_config.rb:30:in `myid'
    /var/chef/cache/cookbooks/zookeeper-cluster/libraries/zookeeper_config.rb:59:in `block (3 levels) in <class:ZookeeperConfig>'
    /var/chef/cache/cookbooks/zookeeper-cluster/libraries/zookeeper_config.rb:58:in `block (2 levels) in <class:ZookeeperConfig>'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
    /var/chef/cache/cookbooks/zookeeper-cluster/libraries/zookeeper_config.rb:45:in `block in <class:ZookeeperConfig>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/zookeeper-cluster/recipes/default.rb

     17: zookeeper_config node['zookeeper-cluster']['service_name'] do |r|
     18:   instance_name node['fqdn']
     19:   owner node['zookeeper-cluster']['service_user']
     20:   group node['zookeeper-cluster']['service_group']
     21: 
     22:   node['zookeeper-cluster']['config'].each_pair { |k, v| r.send(k, v) }
     23:   notifies :restart, "zookeeper_service[#{name}]", :delayed
     24: end
     25: 

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/zookeeper-cluster/recipes/default.rb:17:in `from_file'

    zookeeper_config("zookeeper") do
      provider #<Class:0x0000000658d6c0>
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :zookeeper_config
      cookbook_name "zookeeper-cluster"
      recipe_name "default"
      instance_name "10.0.2.15"
      owner "zookeeper"
      group "zookeeper"
      path "/etc/zookeeper/zoo.properties"
      ensemble ["node-centos65", "node2-centos65"]
      properties {"tickTime"=>2000, "initLimit"=>5, "syncLimit"=>2, "leaderServes"=>"yes", "forceSync"=>"no"}
      leader_port 2888
      election_port 3888
      data_dir "/var/lib/zookeeper"
      client_port 2181
    end


Running handlers:
[2016-01-08T17:36:48+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-08T17:36:48+00:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 06 seconds
[2016-01-08T17:36:48+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-01-08T17:36:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-01-08T17:36:48+00:00] ERROR: tickTime=2000
initLimit=5
syncLimit=2
leaderServes=yes
forceSync=no
dataDir=/var/lib/zookeeper
leaderPort=2888
clientPort=2181
electionPort=3888
server.1:node-centos65:2888:3888
server.2:node2-centos65:2888:3888 (zookeeper-cluster::default line 17) had an error: NoMethodError: undefined method `next' for nil:NilClass
[2016-01-08T17:36:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[vagrant@node-centos65 ~]$ 


```

**Comment by francoisnicholas** [comment]
@johnbellone please do you mind providing any input to my question above?

**Comment by johnbellone** [comment]
You should [take a look at the fixture cookbook for testing](https://github.com/bloomberg/zookeeper-cookbook/blob/master/test/fixtures/test-zookeeper-cluster/recipes/default.rb#L1). The cookbook performs a [hostname lookup](https://github.com/bloomberg/zookeeper-cookbook/blob/master/libraries/zookeeper_config.rb#L30) and takes that index to use for the unique identifier in the Zookeeper ensemble. It looks like you need to add the hostname into that node attribute.

You should separately know that running a two-node Zookeeper ensemble isn't really an approach that is recommended. In general the clusters are built with odd numbers depending on the number of failures you're willing to accept.
